name: catatan_keuangan
description: "Aplikasi Catatan Keuangan MyKas - Multi-Platform PWA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  # Gunakan versi package yang mendukung Flutter 3.24+ / Dart 3
  font_awesome_flutter: ^10.7.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_mykas.png
