name: Build Flutter APK & Deploy Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tarik Code Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter (Lock Version 3.24.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Generate Project Android & Web
        run: flutter create --project-name mykas --platforms=android,web .

      - name: Inject Internet Permission (Android)
        run: sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: flutter pub get

      # 1. BUILD APK NATIVE
      - name: Build APK Native (Release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyKas-Native-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      # 2. BUILD FLUTTER WEB FOR GITHUB PAGES
      - name: Build Flutter Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Upload Web Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy-web:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
